### ISSUE TITLE
Codes on print do not work b/c wrong scaling

### ISSUE THREAD

**Issue by ziggystar** [thawn/ttmp32gme#60]
I printed the codes on my printer and they did not work. They also looked off.

The following code made the codes work, but the page layout is a bit broken because some code images are too small.

I changed this css
```css
.img-24mm {
  max-width: 138px !important;
  min-width: 138px !important;
  max-height: 138px !important;
  min-height: 138px !important;
}
```

to the one given below. This looks more correct to me. The big question is why the size was specified in points. There might be a reason to this.

```css
.img-24mm {
  max-width: 24mm !important;
  min-width: 24mm !important;
  max-height: 24mm !important;
  min-height: 24mm !important;
}
```
